package com.example.demo.enmus;

public enum NotificationType {
    MODIFICATION_REQUEST,
    CANCELLATION_REQUEST,
    REQUEST_ASSIGNED,
    REQUEST_NOTIFICATION,
    ADDITIONAL_INFO_REQUEST,

    REQUEST_APPROVED,
    REQUEST_REJECTED,
    DEMANDE_START,
    MODIFICATION_APPROVED,  
    CANCELLATION_APPROVED,
    MODIFICATION_REJECTED,
    CANCELLATION_REJECTED, DEMANDE_SUPPRESSION, DEMANDE_MODIFICATION
}
